### ISSUE TITLE
have you tried upgrading to High Sierra 12.13.x?

### ISSUE THREAD

**Issue by heisian** [corenel/Z270-HD3-macOS#1]

**Comment by corenel** [comment]
I'm waiting for my graphic card and planning a clean installation for High Sierra. Thus until then I'll stick at 10.12.6.

As far as I know, 10.13 isn't a hard thing since it naively support lots of third-party NVMe SSD. I think what you need to do is have a clean installation with latest MultiBeast and UniBeast.

**Comment by heisian** [comment]
OK, yeah I was able to get High Sierra running on one of my boxes but couldn't get past renaming my GFX card to IGFX0 or the correct name.. seeing the config.plist here I think might well with some of the  DSDTs.

Planning on trying out this build: https://pcpartpicker.com/user/heisian/saved/F6BFdC
